---
images:
  # FIXME: Make sure we use an up-to-date version
  gitInit: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:c4b2183f7c7997bd401d86b33eefb637b3ef2fa90618e875106292cd69a15c14

annotations:
  tekton.dev/pipelines.minVersion: "0.54.0"
  tekton.dev/categories: Git
  tekton.dev/tags: git
  tekton.dev/displayName: "git"
  tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
  artifacthub.io/maintainers: |
      - name: OpenShift Pipeline task maintainers
        email: pipelines-extcomm@redhat.com
  artifacthub.io/provider: Red Hat
  artifacthub.io/recommendations: |
      - url: https://tekton.dev/
  artifacthub.io/category: integration-delivery

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
stepTemplate:
  computeResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
