{{- $workspaces := "workspaces_git_clone" -}}
{{- $params := "params_git_clone" -}}
{{- $results := "results_git_clone" -}}
{{- $env_vars := list
      "params.URL"
      "params.REVISION"
      "params.REFSPEC"
      "params.SUBMODULES"
      "params.DEPTH"
      "params.SPARSE_CHECKOUT_DIRECTORIES"
      "results.COMMITTER_DATE.path"
      "results.URL.path"
      "workspaces.output.path"
}}
{{- $script := "/scripts/report.sh" -}}
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{- if .Values.annotations }}
  annotations:
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: |
    {{ .Chart.Description }}

{{ include "spec_git" ( list . $workspaces $params $results $env_vars $script "output" ) | nindent 2 }}